services:
  database:
    image: postgres:17
    environment:
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: corcoiote
    ports:
      - "5432:5432"
    volumes:
      - corcoiote_data:/var/lib/postgresql/data

volumes:
  corcoiote_data: